USE ROLE SYSADMIN;
USE DATABASE PROVIDER_DB;
USE SCHEMA PUBLIC;

-- Create a warehouse for the data sharing
CREATE OR REPLACE WAREHOUSE DATASHARING WITH
 WAREHOUSE_SIZE = 'XSMALL'
 WAREHOUSE_TYPE = 'STANDARD'
 AUTO_SUSPEND = 60
 AUTO_RESUME = TRUE
 MIN_CLUSTER_COUNT = 1
 MAX_CLUSTER_COUNT = 2
 SCALING_POLICY = 'ECONOMY'
 INITIALLY_SUSPENDED = TRUE;

-- Select from share
SELECT TOP 100 * FROM PUBLIC.SALES;
