USE ROLE SYSADMIN;
USE DATABASE SNOWPROCORE;
USE SCHEMA PUBLIC;

-- ****************************** 1.- Virtual Warehouse ******************************
-- A virtual warehouse is a cluster of compute resources in Snowflake. It is used to execute SQL queries and perform other data processing tasks.
CREATE OR REPLACE WAREHOUSE SNOWPROCORE WITH
    WAREHOUSE_SIZE = 'X-SMALL' -- { XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE }
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = ECONOMY -- { STANDARD | ECONOMY }
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE -- { TRUE | FALSE };
    MAX_CONCURRENCY_LEVEL = 4
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0 
    STATEMENT_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0
;

USE WAREHOUSE SNOWPROCORE;

-- ****************************** 2.- File Format and Stage ******************************
-- When you load data from a file into a table, you must describe the format of the file and specify how the data in the file should be interpreted and processed.
CREATE OR REPLACE FILE FORMAT SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC
 TYPE = 'JSON'
 ENABLE_OCTAL = FALSE
 ALLOW_DUPLICATE  = TRUE
 STRIP_OUTER_ARRAY = TRUE
 STRIP_NULL_VALUES = TRUE
 IGNORE_UTF8_ERRORS = FALSE;

-- A stage is a location in Snowflake where data files are stored. You can use a stage to load data into tables, or to unload data from tables.
CREATE OR REPLACE STAGE SNOWPROCORE.PUBLIC.STAGE_EXTERNAL_ACCOUNTS
  URL='s3://snowflake-s3-sfc-demo-ep/accounts/'
  FILE_FORMAT = SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC;

-- Snowflake allows you to query the contents of a stage using a SELECT statement. This is useful for previewing the contents of a stage before loading the data into a table.
SELECT * FROM @SNOWPROCORE.PUBLIC.STAGE_EXTERNAL_ACCOUNTS (FILE_FORMAT => SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC) SAMPLE(100 ROWS);

-- Apply a transformation to the data in the stage before loading it into a table.
SELECT $1:ACCESSIBLE_BALANCE::FLOAT AS ACCESSIBLE_BALANCE,
       $1:ACCOUNT_BALANCE::FLOAT AS ACCOUNT_BALANCE,
       $1:ACCOUNT_STATUS_CODE::INT AS ACCOUNT_STATUS_CODE,
       $1:ACCOUNT_UID::VARCHAR AS ACCOUNT_UID,
       $1:CDIC_HOLD_STATUS_CODE::INT AS CDIC_HOLD_STATUS_CODE,
       $1:CURRENCY_CODE::INT AS CURRENCY_CODE,
       $1:CURRENT_CDIC_HOLD_AMOUNT::FLOAT AS CURRENT_CDIC_HOLD_AMOUNT,
       $1:DEPOSITOR_ID::VARCHAR AS DEPOSITOR_ID,
       $1:INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE::INT AS INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,
       $1:PRODUCT_CODE::INT AS PRODUCT_CODE,
       $1:REGISTERED_ACCOUNT_FLAG::BOOLEAN AS REGISTERED_ACCOUNT_FLAG,
       $1:REGISTERED_PLAN_TYPE_CODE::INT AS REGISTERED_PLAN_TYPE_CODE
FROM @SNOWPROCORE.PUBLIC.STAGE_EXTERNAL_ACCOUNTS;

-- ****************************** 3.- Loading data Into a Table ******************************
CREATE OR REPLACE TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_INTERNAL_RAW (
    PAYLOAD VARIANT,
    LOAD_DATE TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

COPY INTO SNOWPROCORE.PUBLIC.ACCOUNTS_INTERNAL_RAW (PAYLOAD)
FROM (
    SELECT $1 AS PAYLOAD
    FROM @SNOWPROCORE.PUBLIC.STAGE_EXTERNAL_ACCOUNTS (FILE_FORMAT => SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC)
)
FILE_FORMAT = SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC
--PATTERN = '.*.json.gz'
PATTERN = '.*.json'
ON_ERROR = 'skip_file'
PURGE = FALSE;

-- ****************************** 4.- Querying the Table ******************************
SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS_INTERNAL_RAW;

LIST @SNOWPROCORE.PUBLIC.STAGE_INTERNAL_ACCOUNTS;

-- ****************************** 5.- Flattening the RAW Table ******************************
CREATE OR REPLACE TABLE SNOWPROCORE.PUBLIC.ACCOUNTS (
    ACCESSIBLE_BALANCE                         FLOAT,
    ACCOUNT_BALANCE                            FLOAT,
    ACCOUNT_STATUS_CODE                        INT,
    ACCOUNT_UID                                VARCHAR,
    CDIC_HOLD_STATUS_CODE                      INT,
    CURRENCY_CODE                              INT,
    CURRENT_CDIC_HOLD_AMOUNT                   FLOAT,
    DEPOSITOR_ID                               VARCHAR,
    INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE INT,
    PRODUCT_CODE                               INT,
    REGISTERED_ACCOUNT_FLAG                    BOOLEAN,
    REGISTERED_PLAN_TYPE_CODE                  INT
);

INSERT INTO SNOWPROCORE.PUBLIC.ACCOUNTS
SELECT $1:ACCESSIBLE_BALANCE::FLOAT AS ACCESSIBLE_BALANCE,
       $1:ACCOUNT_BALANCE::FLOAT AS ACCOUNT_BALANCE,
       $1:ACCOUNT_STATUS_CODE::INT AS ACCOUNT_STATUS_CODE,
       $1:ACCOUNT_UID::VARCHAR AS ACCOUNT_UID,
       $1:CDIC_HOLD_STATUS_CODE::INT AS CDIC_HOLD_STATUS_CODE,
       $1:CURRENCY_CODE::INT AS CURRENCY_CODE,
       $1:CURRENT_CDIC_HOLD_AMOUNT::FLOAT AS CURRENT_CDIC_HOLD_AMOUNT,
       $1:DEPOSITOR_ID::VARCHAR AS DEPOSITOR_ID,
       $1:INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE::INT AS INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE,
       $1:PRODUCT_CODE::INT AS PRODUCT_CODE,
       $1:REGISTERED_ACCOUNT_FLAG::BOOLEAN AS REGISTERED_ACCOUNT_FLAG,
       $1:REGISTERED_PLAN_TYPE_CODE::INT AS REGISTERED_PLAN_TYPE_CODE
FROM SNOWPROCORE.PUBLIC.ACCOUNTS_INTERNAL_RAW;

SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS;

-- ****************************** 6.- Data Protection ****************************** 
-- Change some records in the table
UPDATE SNOWPROCORE.PUBLIC.ACCOUNTS
SET ACCOUNT_BALANCE = 0
WHERE CDIC_HOLD_STATUS_CODE = 1;

-- Time travel to see the changes
SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS BEFORE(STATEMENT => '');

INSERT OVERWRITE INTO SNOWPROCORE.PUBLIC.ACCOUNTS
SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS BEFORE(STATEMENT => '');

SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS;

-- ****************************** 7.- Data Governance ******************************
-- Dynamic Data Masking
USE ROLE SYSADMIN;
USE DATABASE SNOWPROCORE;
USE SCHEMA PUBLIC;

-- Create a masking policy that prevents non-administrative users from seeing the actual values in the id column of the account table.
CREATE OR REPLACE MASKING POLICY BALANCE_MASK AS (VAL FLOAT) RETURNS FLOAT -> 
    CASE
    WHEN CURRENT_ROLE() IN ('SYSADMIN','ACCOUNTADMIN') THEN VAL
    ELSE 0.0
END;

-- Apply masking to the account table
ALTER TABLE IF EXISTS SNOWPROCORE.PUBLIC.ACCOUNTS MODIFY COLUMN ACCESSIBLE_BALANCE SET MASKING POLICY BALANCE_MASK;
ALTER TABLE IF EXISTS SNOWPROCORE.PUBLIC.ACCOUNTS MODIFY COLUMN ACCOUNT_BALANCE SET MASKING POLICY BALANCE_MASK;

-- Test the masking policy
SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS;

USE ROLE ANALYST;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWPROCORE;
USE SCHEMA PUBLIC;

SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS;
