USE ROLE SYSADMIN;
USE DATABASE SNOWPROCORE;
USE SCHEMA PUBLIC;
USE WAREHOUSE SNOWPROCORE;

CREATE TABLE SNOWPROCORE.PUBLIC.PRODUCT_CODE AS
SELECT DISTINCT PRODUCT_CODE FROM SNOWPROCORE.PUBLIC.ACCOUNTS ORDER BY 1 ASC;
