USE ROLE SYSADMIN;

DROP WAREHOUSE IF EXISTS SNOWPROCORE;
DROP DATABASE  IF EXISTS SNOWPROCORE CASCADE;

-- Creating a new virtual warehouse with the following properties
CREATE OR REPLACE WAREHOUSE SNOWPROCORE WITH
    WAREHOUSE_SIZE = 'X-SMALL' -- { XSMALL | SMALL | MEDIUM | LARGE | XLARGE | XXLARGE | XXXLARGE | X4LARGE | X5LARGE | X6LARGE }
    MIN_CLUSTER_COUNT = 1
    MAX_CLUSTER_COUNT = 2
    SCALING_POLICY = ECONOMY -- { STANDARD | ECONOMY }
    AUTO_SUSPEND = 180
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE -- { TRUE | FALSE };
    --MAX_CONCURRENCY_LEVEL = <num>
    STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0 
    STATEMENT_TIMEOUT_IN_SECONDS = 600 -- DEFAULT VALUE = 0
;

USE WAREHOUSE SNOWPROCORE;

-- Creating a new database with the following properties
CREATE OR REPLACE DATABASE SNOWPROCORE
    DATA_RETENTION_TIME_IN_DAYS = 2; -- We will discuss what DATA_RETENTION_TIME_IN_DAYS means in futher sessions

-- Creating a table out of a sample data
CREATE OR REPLACE TABLE SNOWPROCORE.PUBLIC.CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.CUSTOMER;

SELECT COUNT(*) FROM SNOWPROCORE.PUBLIC.CUSTOMER;

-- You can change the warehouse size on the fly, be aware this incurs in a cost
ALTER WAREHOUSE SNOWPROCORE SET WAREHOUSE_SIZE = XXLARGE;

CREATE OR REPLACE TABLE SNOWPROCORE.PUBLIC.LINEITEM AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;

ALTER WAREHOUSE SNOWPROCORE SET WAREHOUSE_SIZE = XSMALL;

SELECT COUNT(*) FROM SNOWPROCORE.PUBLIC.LINEITEM;

-- ***** Different CACHING *****
-- METADATA CACHE
ALTER WAREHOUSE SNOWPROCORE SUSPEND;
SELECT MAX(L_SHIPDATE), MIN(L_SHIPDATE) FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM;

-- RESULT SET CACHE
SELECT * FROM SNOWPROCORE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

ALTER WAREHOUSE SNOWPROCORE SUSPEND;

SELECT * FROM SNOWPROCORE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

-- DISABLE RESULT SET CACHE
ALTER SESSION SET USE_CACHED_RESULT = FALSE;

ALTER WAREHOUSE SNOWPROCORE SUSPEND;
SELECT * FROM SNOWPROCORE.PUBLIC.CUSTOMER WHERE C_MKTSEGMENT = 'AUTOMOBILE';

ALTER SESSION SET USE_CACHED_RESULT = TRUE;
