-- 1.- Creating a custom role analyst
USE ROLE SECURITYADMIN;
CREATE OR REPLACE ROLE ANALYST
 COMMENT  = 'ANALYST';

-- 2.- Grant role to user and role SYSADMIN
USE ROLE SECURITYADMIN;
GRANT ROLE ANALYST TO ROLE SYSADMIN;
GRANT ROLE ANALYST TO USER ENRIQUEP;

-- 3.- Granting access to tables
USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE SNOWPROCORE TO ROLE ANALYST;
GRANT USAGE ON SCHEMA SNOWPROCORE.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA SNOWPROCORE.PUBLIC TO ROLE ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SNOWPROCORE.PUBLIC TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE SNOWPROCORE TO ROLE ANALYST;
