-- Create database and schemas
USE ROLE SYSADMIN;

CREATE OR REPLACE WAREHOUSE COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 2
  SCALING_POLICY = 'STANDARD'
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Compute WH for FOOBAR';

USE WAREHOUSE COMPUTE_WH; -- COMES WITH SNOWFLAKE TRIAL ACCOUNT

CREATE OR REPLACE DATABASE FOOBAR_DB;

USE SCHEMA FOOBAR_DB.PUBLIC; -- COMES WITH EVERY SNOWFLAKE DATABASE;

-- Note: MUST BE RUN BY ACCOUNTADMIN to allow browsing to containers via HTTPS
USE ROLE ACCOUNTADMIN;

CREATE SECURITY INTEGRATION IF NOT EXISTS SNOWSERVICES_INGRESS_OAUTH
  TYPE = OAUTH
  OAUTH_CLIENT = SNOWSERVICES_INGRESS
  ENABLED = TRUE;

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FOOBAR_DB;
USE SCHEMA FOOBAR_DB.PUBLIC;

CREATE STAGE IF NOT EXISTS FOOBAR_DB.PUBLIC.MODELS
 DIRECTORY = (ENABLE = TRUE)
 ENCRYPTION = (TYPE='SNOWFLAKE_SSE');

-- Stage to store yaml specs
CREATE STAGE IF NOT EXISTS FOOBAR_DB.PUBLIC.SPECS
 DIRECTORY = (ENABLE = TRUE)
 ENCRYPTION = (TYPE='SNOWFLAKE_SSE');

CREATE OR REPLACE IMAGE REPOSITORY FOOBAR_DB.PUBLIC.IMAGES;

USE ROLE ACCOUNTADMIN;
CREATE COMPUTE POOL COMPUTE_POOL_FOOBAR
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE
  AUTO_SUSPEND_SECS = 900
  COMMENT = 'Compute pool for FOOBAR';

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON COMPUTE POOL COMPUTE_POOL_FOOBAR TO ROLE SYSADMIN;
GRANT MONITOR ON COMPUTE POOL COMPUTE_POOL_FOOBAR TO ROLE SYSADMIN;

-- Creating user and granting SYSADMIN privileges this will be use through the Snowflake CLI
USE ROLE USERADMIN;
CREATE OR REPLACE USER dockeruser
 PASSWORD = 'superdocker' DEFAULT_ROLE = 'SYSADMIN' 
 DEFAULT_WAREHOUSE = COMPUTE_WH
 MUST_CHANGE_PASSWORD = FALSE
 DEFAULT_NAMESPACE = 'FOOBAR_DB.PUBLIC';

-- Granting privileges to the user
USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER dockeruser;

USE ROLE ACCOUNTADMIN;
SHOW COMPUTE POOLS;
SHOW INTEGRATIONS LIKE '%SERVICE%';
DESC INTEGRATION SNOWSERVICES_INGRESS_OAUTH;
SHOW IMAGE REPOSITORIES;
