-- Create database and schemas
USE ROLE SYSADMIN;

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 2
  SCALING_POLICY = 'STANDARD'
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Compute WH for FOOBAR';

USE WAREHOUSE COMPUTE_WH; -- COMES WITH SNOWFLAKE TRIAL ACCOUNT

CREATE OR REPLACE DATABASE FOOBAR_DB;

-- Note: MUST BE RUN BY ACCOUNTADMIN to allow browsing to containers via HTTPS
USE ROLE ACCOUNTADMIN;

-- Create security integration for OAuth
CREATE SECURITY INTEGRATION IF NOT EXISTS SNOWSERVICES_INGRESS_OAUTH
  TYPE = OAUTH
  OAUTH_CLIENT = SNOWSERVICES_INGRESS
  ENABLED = TRUE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE SYSADMIN;

-- Create network policy to allow egress access to Snowflake
CREATE OR REPLACE NETWORK RULE SNOWFLAKE_EGRESS_ACCESS
  MODE = EGRESS
  TYPE = HOST_PORT
  VALUE_LIST = ('<YOUR_ACCOUNT>.snowflakecomputing.com');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SNOWFLAKE_EGRESS_ACCESS_INTEGRATION
  ALLOWED_NETWORK_RULES = (SNOWFLAKE_EGRESS_ACCESS)
  ENABLED = true;

GRANT USAGE ON INTEGRATION SNOWFLAKE_EGRESS_ACCESS_INTEGRATION TO ROLE SYSADMIN;

USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FOOBAR_DB;
USE SCHEMA FOOBAR_DB.PUBLIC;

-- Stage to store yaml specs
CREATE STAGE IF NOT EXISTS FOOBAR_DB.PUBLIC.SPECS
 DIRECTORY = (ENABLE = TRUE)
 ENCRYPTION = (TYPE='SNOWFLAKE_SSE');

CREATE IMAGE REPOSITORY IF NOT EXISTS FOOBAR_DB.PUBLIC.IMAGES;

USE ROLE ACCOUNTADMIN;
CREATE COMPUTE POOL COMPUTE_POOL_FOOBAR
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_XS
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE
  AUTO_SUSPEND_SECS = 900
  COMMENT = 'Compute pool for FOOBAR';

USE ROLE ACCOUNTADMIN;
GRANT USAGE, MONITOR, OPERATE ON COMPUTE POOL COMPUTE_POOL_FOOBAR TO ROLE SYSADMIN;

-- Creating user and granting SYSADMIN privileges this will be use through the Snowflake CLI
USE ROLE USERADMIN;
CREATE USER IF NOT EXISTS dockeruser
 PASSWORD = 'superdocker' DEFAULT_ROLE = 'SYSADMIN' 
 DEFAULT_WAREHOUSE = COMPUTE_WH
 MUST_CHANGE_PASSWORD = FALSE
 DEFAULT_NAMESPACE = 'FOOBAR_DB.PUBLIC';

-- Granting privileges to the user
USE ROLE SECURITYADMIN;
GRANT ROLE SYSADMIN TO USER dockeruser;

-- Network rules
USE ROLE ACCOUNTADMIN;
CREATE OR REPLACE NETWORK RULE ALLOW_PUBLIC_RULE
  MODE = INGRESS
  TYPE = IPV4
  VALUE_LIST = ('0.0.0.0/0');

CREATE OR REPLACE NETWORK POLICY ALLOW_PUBLIC_POLICY
  ALLOWED_NETWORK_RULE_LIST = ('ALLOW_PUBLIC_RULE');

ALTER USER dockeruser SET NETWORK_POLICY = ALLOW_PUBLIC_POLICY;

SHOW PARAMETERS LIKE 'network_policy' IN USER dockeruser;

USE ROLE ACCOUNTADMIN;
SHOW COMPUTE POOLS;
SHOW INTEGRATIONS LIKE '%SERVICE%';
DESC INTEGRATION SNOWSERVICES_INGRESS_OAUTH;
SHOW IMAGE REPOSITORIES;
