USE ROLE SYSADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE FOOBAR_DB;
USE SCHEMA FOOBAR_DB.PUBLIC;

SHOW IMAGE REPOSITORIES IN SCHEMA;

DROP SERVICE IF EXISTS DBT_SERVICE;

-- Before running the following commands be sure to upload the image to the repository and upload the spcs file to the stage
CREATE SERVICE DBT_SERVICE
	IN COMPUTE POOL COMPUTE_POOL_FOOBAR
	FROM @SPECS
	SPEC = 'dbt-spec.yaml'
	MIN_INSTANCES = 1
	MAX_INSTANCES = 1;

SHOW SERVICES IN SCHEMA;

-- Checking logs
USE ROLE SYSADMIN;
USE DATABASE FOOBAR_DB;
USE SCHEMA FOOBAR_DB.PUBLIC;
SELECT SYSTEM$GET_SERVICE_STATUS('DBT_SERVICE');
SELECT SYSTEM$GET_SERVICE_LOGS('FOOBAR_DB.PUBLIC.DBT_SERVICE', 0, 'dbt-runner', 100);
SELECT SYSTEM$GET_SERVICE_LOGS('FOOBAR_DB.PUBLIC.DBT_SERVICE', 0, 'dbt-docs', 100);

# Getting public endpoints
SHOW SERVICES LIKE 'DBT_SERVICE';
SELECT "public_endpoints" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

-- Suspending service so it doesn't incur charges
USE ROLE ACCOUNTADMIN;
ALTER COMPUTE POOL IF EXISTS COMPUTE_POOL_FOOBAR SUSPEND;
