USE ROLE SYSADMIN;

-- CREATE WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS LOADING_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'-- 'XSMALL' | 'SMALL' | 'MEDIUM' | 'LARGE' | 'XLARGE' | 'XXLARGE' | 'XXXLARGE'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 3
  SCALING_POLICY = 'STANDARD' -- 'STANDARD' | 'ECONOMY'
  INITIALLY_SUSPENDED = TRUE;

USE WAREHOUSE LOADING_WH;

-- CREATE DATABASE
CREATE DATABASE IF NOT EXISTS LOADING_DB COMMENT = 'Loading Database'
    DATA_RETENTION_TIME_IN_DAYS = 1;

USE DATABASE LOADING_DB;

-- CREATE SCHEMA
CREATE OR REPLACE SCHEMA LOADING_DB.RAW COMMENT = 'Loading Schema'
    DATA_RETENTION_TIME_IN_DAYS = 2;

USE SCHEMA LOADING_DB.RAW;

-- CREATE CSV FILE FORMAT
CREATE OR REPLACE FILE FORMAT LOADING_DB.RAW.CSV_UNLOADING_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    TRIM_SPACE = TRUE
    COMPRESSION = 'NONE';

CREATE STAGE IF NOT EXISTS LOADING_DB.RAW.FILES_STAGE;

-- UPLOAD A CSV
PUT file:///Users/eplata/Developer/personal/snowflake-sample-code/sql/02-loading/data_0_0_0.csv @LOADING_DB.RAW.FILES_STAGE/ AUTO_COMPRESS=FALSE;

-- CREATE TABLE
CREATE OR REPLACE TABLE LOADING_DB.RAW.ACCOUNTS_RAW
(
    ACCESSIBLE_BALANCE                         VARCHAR,
    ACCOUNT_BALANCE                            VARCHAR,
    ACCOUNT_STATUS_CODE                        VARCHAR,
    ACCOUNT_UID                                VARCHAR,
    CDIC_HOLD_STATUS_CODE                      VARCHAR,
    CURRENCY_CODE                              VARCHAR,
    CURRENT_CDIC_HOLD_AMOUNT                   VARCHAR,
    DEPOSITOR_ID                               VARCHAR,
    INSURANCE_DETERMINATION_CATEGORY_TYPE_CODE VARCHAR,
    PRODUCT_CODE                               VARCHAR,
    REGISTERED_ACCOUNT_FLAG                    VARCHAR,
    REGISTERED_PLAN_TYPE_CODE                  VARCHAR,
    FILE_NAME                                  VARCHAR,
    FILE_ROW_NUMBER                            VARCHAR
);

-- LOAD DATA MANUALLY

-- UNLOADING DATA
COPY INTO @LOADING_DB.RAW.FILES_STAGE/ FROM (SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS_RAW) FILE_FORMAT = (FORMAT_NAME = 'LOADING_DB.RAW.CSV_UNLOADING_FORMAT');

LS @LOADING_DB.RAW.FILES_STAGE;
RM @LOADING_DB.RAW.FILES_STAGE/data_0_0_0.csv/data_0_0_0.csv;

GET @LOADING_DB.RAW.FILES_STAGE/data_0_0_0.csv file:////Users/eplata/Developer/personal/snowflake-sample-code/sql/02-loading;
