USE ROLE SYSADMIN;
USE WAREHOUSE SNOWPROCORE;
USE DATABASE SNOWPROCORE;
USE SCHEMA SNOWPROCORE.PUBLIC;

-- ****************************** 1.- Creating a stage with directory table ******************************
CREATE OR REPLACE STAGE SNOWPROCORE.PUBLIC.JSON_FILES_STAGE
  DIRECTORY = (ENABLE = TRUE);

-- ****************************** 2.- File Format ******************************
CREATE OR REPLACE FILE FORMAT SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC
 TYPE = 'JSON'
 ENABLE_OCTAL = FALSE
 ALLOW_DUPLICATE  = TRUE
 STRIP_OUTER_ARRAY = TRUE
 STRIP_NULL_VALUES = TRUE
 IGNORE_UTF8_ERRORS = FALSE;

-- ****************************** 3.- Loading file from local machine to Snowflake stage ******************************
PUT file://///Users/eplata/Developer/personal/snowflake-sample-code/sql/06-advance-sql/SNOWBANK_PUBLIC_ACCOUNTS_1.json @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE;

LS @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE;

-- ****************************** 4.- Creating table from file structure ******************************
CREATE OR REPLACE TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
  USING TEMPLATE (
    SELECT ARRAY_AGG(object_construct(*))
      FROM TABLE(
        INFER_SCHEMA(
          LOCATION=>'@JSON_FILES_STAGE/SNOWBANK_PUBLIC_ACCOUNTS_1.json.gz',
          FILE_FORMAT=>'SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC'
        )
	)
) ENABLE_SCHEMA_EVOLUTION = TRUE;;

DESCRIBE TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION;
SHOW TABLES IN SNOWPROCORE.PUBLIC STARTS WITH 'ACCOUNTS_SCHEMA_EVOLUTION'; -- check parameter ENABLE_SCHEMA_EVOLUTION

-- ****************************** 5.- Copying data into table ******************************
COPY INTO SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
  FROM @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE
  FILE_FORMAT = SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  PATTERN = '.*.json.gz'
  PURGE = TRUE;

SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION;

LS @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE;

-- ****************************** 6.- Adding new file that adds new columns to table ******************************
-- NOTE: LOOK INTO THE SECOND JSON FILE AND NOTICE ATTRIBUTE "ACCOUNT_CHANGE_DATE"
PUT file://///Users/eplata/Developer/personal/snowflake-sample-code/sql/06-advance-sql/SNOWBANK_PUBLIC_ACCOUNTS_2.json @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE;

LS @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE;

COPY INTO SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
  FROM @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE
  FILE_FORMAT = SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC
  MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
  PATTERN = '.*.json.gz'
  PURGE = TRUE;

DESCRIBE TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION;

SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION ORDER BY ACCOUNT_CHANGE_DATE ASC;
