USE ROLE SYSADMIN;
USE WAREHOUSE SNOWPROCORE;
USE DATABASE SNOWPROCORE;
USE SCHEMA PUBLIC;

-- Previusly we created a table called "SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER" with the following ddl:
-- What is the problem with this? is this dynamic? what if the source changes but we would like to add new columns to subsequent objects through our pipelines?

-- CREATE OR REPLACE TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER (
-- 	ACCESSIBLE_BALANCE NUMBER(8,2),
-- 	ACCOUNT_BALANCE NUMBER(8,2),
-- 	ACCOUNT_STATUS_CODE NUMBER(1,0),
-- 	ACCOUNT_UID VARCHAR(16777216),
-- 	CDIC_HOLD_STATUS_CODE NUMBER(1,0),
-- 	CURRENCY_CODE NUMBER(1,0)
-- );

-- Let's create a DYNAMIC TABLE that reads from the stream
CREATE OR REPLACE DYNAMIC TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER_DYNAMIC_TABLE
 COMMENT = 'This is a dynamic table'
 INITIALIZE = ON_CREATE
 REFRESH_MODE = AUTO
 WAREHOUSE = SNOWPROCORE
 TARGET_LAG = '60 seconds'
 AS
  	SELECT *
	FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION; -- Simple but query could be quite complex and with joins, etc.

-- Let's check the original table
SELECT count(*) FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION;

-- Let's check the dynamic table
SELECT COUNT(*) FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER_DYNAMIC_TABLE;

SELECT * FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER_DYNAMIC_TABLE;

-- Let's a file to the stage
PUT file://///Users/eplata/Developer/personal/snowflake-sample-code/sql/06-advance-sql/SNOWBANK_PUBLIC_ACCOUNTS_3.json @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE;

-- Runing the copy into manually to see if the dynamic table is working
COPY INTO SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION
FROM @SNOWPROCORE.PUBLIC.JSON_FILES_STAGE
FILE_FORMAT = SNOWPROCORE.PUBLIC.FILE_FORMAT_JSON_GENERIC
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE
PATTERN = '.*.json.gz'
PURGE = TRUE;

-- Let's check the original table
SELECT COUNT(*) FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SCHEMA_EVOLUTION;
SELECT COUNT(*) FROM SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER_DYNAMIC_TABLE;

-- CLEAN UP
ALTER DYNAMIC TABLE SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER_DYNAMIC_TABLE SUSPEND;
DROP TABLE IF EXISTS SNOWPROCORE.PUBLIC.ACCOUNTS_SILVER_DYNAMIC_TABLE;
