USE ROLE ANALYST;
SHOW DATABASES;
USE DATABASE SNOWFLAKE;
SHOW SCHEMAS; -- ACCOUNT_USAGE AND OTHER SCHEMAS ARE NOT VISIBLE

-- USING THE ACCOUNTADMIN ROLE
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE;
USE WAREHOUSE SNOWPROCORE;

SHOW SCHEMAS; -- ACCOUNT_USAGE AND OTHER SCHEMAS ARE VISIBLE
USE SCHEMA ACCOUNT_USAGE;

SHOW TABLES; -- THIS IS A SNOWFLAKE SHARED DB (FUTURE CONCEPT) IN THIS CASE THE SOURCE OWNER (SNOWFLAKE) IS ONLY ALLOWING TO SEE THE VIEWS FROM A DATABASE.
SHOW VIEWS;

-- IMPORTANT VIEWS
SELECT * FROM WAREHOUSE_METERING_HISTORY LIMIT 10; -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM METERING_DAILY_HISTORY LIMIT 10; -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM DATABASE_STORAGE_USAGE_HISTORY LIMIT 10; -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM ACCESS_HISTORY LIMIT 10; -- THIS VIEW IS ASKED DURING THE EXAM
SELECT * FROM QUERY_HISTORY LIMIT 10; -- THIS VIEW IS ASKED DURING THE EXAM ********* (UI)

-- LETS EXPLORE THE INFORMATION SCHEMA
USE ROLE SYSADMIN;
USE DATABASE SNOWPROCORE;
USE SCHEMA INFORMATION_SCHEMA;
USE WAREHOUSE SNOWPROCORE;
SELECT * FROM INFORMATION_SCHEMA.TABLES LIMIT 10; -- EXPLORE SOME OF THE COLUMNS OF THIS VIEW
